import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export const metadata = {
  icons: {
    icon: '/image/logo.png',
  },
  title: "Alokito Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body >
        <Navbar/>
        <div className="flex justify-center items-center mt-20">
        {children}
        </div>
       
        <Footer/>
        
      </body>
      
      
    </html>
  );
}
