import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import NavBar from "@/components/navBar/navbar";

export const metadata = {
  icons: {
    icon: '/image/logo.png',
  },
  title: "Alokito Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body >
        <NavBar/>
        <div className="flex justify-center items-center mt-20">
        {children}
        </div>
       
        <Footer/>
        
      </body>
      
      
    </html>
  );
}
